### ISSUE TITLE
E/CameraService: setTorchMode: torch mode of camera 0 is not available because camera is in use

### ISSUE THREAD

**Issue by matejbart** [ahoyconference/cordova-ahoyrtc#1]
Hi,

I'm using the .aar lib out of this repo for my native android project. When I try to call the method `setTorchMode(boolean enabled)` at `AhoySession.class` , no camera flash light is going to be turned on/off, but instead I get an error in the log:
`E/CameraService: setTorchMode: torch mode of camera 0 is not available because camera is in use`

I can assure, that when I'm calling the method, the back camera is already opened and streaming. This stackoverflow post (https://stackoverflow.com/questions/33324647/flashlight-camera2-api) might address the (same) camera torch mode issue.

I would appreciate your response. 

BR

**Comment by kapejod** [comment]
Fixed with AhoySDK 1.16 for Android.
